### ISSUE TITLE
imitate() needs to be placed below listeners in order to work

### ISSUE THREAD

**Issue by mspoulsen** [staltz/xstream#41] opened 2016-05-31 10:24 UTC
Hi,

I keep running into this issue and forgetting to place imitate() at the bottom...any chance this could be fixed?

http://www.webpackbin.com/4JzdyLUXZ

Thanks!

**Comment by staltz** [comment] 2016-05-31 11:08
This is a duplicate of #5.

No worries, I'll start working on it. :)

**Closed by staltz** 2016-05-31 11:08 UTC
