### ISSUE TITLE
xs.merge() bug - fixed by debug()

### ISSUE THREAD

**Issue by mspoulsen** [staltz/xstream#74] opened 2016-07-09 20:14 UTC
Here I pass in a stream of actions to my component but my component is not initialized correctly when I use xs.merge. If I don't it is initialized fine:
http://www.webpackbin.com/E1oZ4rc8Z

Here we see that adding -debug() fixes the issue:
http://www.webpackbin.com/VybPuSqLZ

**Comment by Hypnosphi** [comment] 2016-07-10 00:00
making `foo$` the first argument of another `xs.merge` (the one in model) helps, too. Seems like only one stream of three gets actual values. Looks very similar to the problem described by @TylorS in https://github.com/staltz/xstream/pull/60

**Comment by Hypnosphi** [comment] 2016-07-10 00:39
I've simlified the example a bit further: http://www.webpackbin.com/NkJyDFqIW

Weird, but it gets reproduced only if you have at least three merged derivative streams

**Comment by Hypnosphi** [comment] 2016-07-10 01:35
Or even so: http://www.webpackbin.com/V1ks-59L-
`MergeProducer` doesn't complete second time because `-1 !== 0` [here](https://github.com/staltz/xstream/blob/master/src/core.ts#L124), and everything breaks afterwards.

I suppose, `ac` should be set not [in `_stop`](https://github.com/staltz/xstream/blob/master/src/core.ts#L124), but in `_start`, right before the inner streams get listened to.

**Comment by mspoulsen** [comment] 2016-07-10 08:34
If the stream is merged with a non-completing stream then debug() does not help:

```javascript
const action$       = xs.merge(intent$, xs.never()).debug();
```

http://www.webpackbin.com/E1lCIgjLb

**Comment by Hypnosphi** [comment] 2016-07-10 10:45
Well, in this case behaviour is as expected, it's totally different stream and it behaves differently

**Comment by Hypnosphi** [comment] 2016-07-10 10:46
See #59 =)

**Comment by mspoulsen** [comment] 2016-07-10 10:56
I just don't get it :worried: 

```javascript
const state$        = model(xs.merge(sources.intent$, controls.intent$)).debug();
```
In my app I have actions coming from the parent (sources) and from a child component (controls). I want to merge these, pass them to model, create reducers from them and fold over the reducers (the usual pattern). This time I don't see that I have multiple listeners, so what am I doing wrong?

**Comment by ntilwalli** [comment] 2016-07-10 14:32
I updated the example posted in the gitter this morning (with comments) so it works:  http://www.webpackbin.com/V1LfcrsL-  

I'm not convinced there is a `merge` bug. `xs.of`-sourced streams like `action$` must be `remember`ed or `compose`d with a `delay` if they have multiple consumers so wiring can complete.

**Comment by Hypnosphi** [comment] 2016-07-10 16:45
@ntilwalli to get convinced that the bug is a real thing, take a look at my latest example. The merged stream doesn't complete when it should

**Closed** 2016-07-11 19:43 UTC

**Comment by staltz** [comment] 2016-07-11 20:17
Fixed thanks to @Hypnosphi! His PR made me open my eyes to some other issues, so I'll bundle his fix with some of mine and release a new patch version.
